services:
  postgres:
    container_name: demo-nestjs-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: nest-test

  redis:
    container_name: demo-nestjs-redis
    image: redis:7-alpine
    command: redis-server --requirepass redispassword
    restart: unless-stopped
    ports:
      - "6379:6379"
